### ISSUE TITLE
Allow custom Content-Length with empty HEAD response

### ISSUE THREAD

**Issue by MightyPork** [tomaka/rouille#230]
When sending a response to HEAD, the `Content-Type` header MAY describe the corresponding GET payload length ([MDN]). Adding a `Content-Length` header to a `Response`, however, has no effect, because that header is always discarded. (this may need a fix in the tiny-http library)

[MDN]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

**Comment by MightyPork** [comment]
disregard, I discovered HEAD is somehow magically handled by tiny-http (???). I was only making things harder.

**Comment by ColonelThirtyTwo** [comment]
This is still an issue. A server should be able to set the Content-Length of a HEAD response without providing tiny-http a stream, since it can be a lot more efficient to get the size via other means (ex. stat-ing a file).

As a workaround, you can use `ResponseBody::from_reader_and_size(std::io::Cursor::new(vec![]), size)`.
