### ISSUE TITLE
rustfmt doesn't work

### ISSUE THREAD

**Issue by krruzic** [tomaka/rouille#240]
When I format code with the `router!` macro, the code within the macro doesn't format at all.

**Comment by krruzic** [comment]
Okay, so did some basic research and its a problem with macros in general. Yew has a similar problem with `html!` and someone has made a library that allows constructing the macro contents through a builder pattern with no macros needed. Would something similar be possible to implement?

**Comment by bradfier** [comment]
`rustfmt` breaks down here (and in the other cases you've identified) because there's actually no reason the contents of a Macro actually has to be Rust code, so `rustfmt` doesn't know to format it accordingly.

The `router!` macro is one of the most complex parts of Rouille, it expands to static code which evaluates every route in the block in order, handles all the argument extraction and parsing, and dispatches the first route that fully matches.

Since this is all imperative there's no `Route` structure or object we could easily create to allow a builder pattern, we'd need to rewrite the router logic in a different way. I'd be happy to accept patches to do this but I expect it's a big chunk of work.

In the near term, my suggestion would be to keep the amount of code actually inside the `router!` macro to a minimum, for example most of my projects use a format something like this:

```rust
router!(request,
        (GET) ["/events"] => {
            let events = fetch_events()?;
            Ok(Response::json(&events))
        },
        (POST) ["/events", profile_id: Uuid] => {
            let event = create_profile_event(request)?;
            Ok(Response::json(&event))
        },
)
```

Where the logic is all pushed out to regular functions that just take a `Request` and return a `Result<Response, Error>`, this means you have a minimum amount of code inside the macro to actually format.
